### PR TITLE
Move jokes to JSON file and use `.gitignore`

### PR DESCRIPTION
**Pull request by Chiroyce1**
Tested and it works well, this PR removes the venv/ folder and also adds the `venv` folder  to the `.gitignore`.  

The reason it shouldn't be included is because it contains a Python executable and all the libraries/packages you are using, so it isn't a good idea to include such huge files in your repo, when anyone who runs this will already have Python installed on their device.

### CODE REVIEW

**Review by leahcimto — APPROVED** [review]
Thanks so much for doing this!

**Comment by leahcimto** [comment]
@Chiroyce1 is it okay to delete .replit and replit.nix too?

**Comment by Chiroyce1** [comment]
There's nothing wrong in doing so, but since you are running the API on Replit, these files can be useful there (.replit contains the command to run  the server and some other metadata, .replit.nix contains the packages necessary to run the server on Replit) - so for now, keeping it is a good idea. 

The reason I deleted venv/ was because it had no use, and was taking up a lot of unnecessary space on the repository.

**Comment by leahcimto** [comment]
I made a pr and merged, but the repl couldn't run so reverting now...

**Comment by Chiroyce1** [comment]
> I made a pr and merged, but the repl couldn't run so reverting now...

Wait - before that, try to run `python3 main.py` in the shell

**Comment by leahcimto** [comment]
> > I made a pr and merged, but the repl couldn't run so reverting now...
> 
> Wait - before that, try to run `python3 main.py` in the shell Also we could add these 2 files to the gitigonore, so try that out. Then they will be present on the server, but not on github.

Okay, I'll try that

**Comment by leahcimto** [comment]
I get `ModuleNotFoundError: No module named 'flask'`

**Comment by leahcimto** [comment]
I'm just going to revert it now

**Pull request merged**
